version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: postgres #${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: 12345678 #${POSTGRES_PASSWORD:-changeme}
    volumes:
       - D:\docker\volumes\pgadmin4\data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - /root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped



