version: '3'

services:
  postgres:
    image: postgres:11-alpine
    ports:
      - "${POSTGRES_DB:-5432}:5432"
    network_mode: bridge
    container_name: postgres-container
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
      POSTGRES_DB: "${POSTGRES_DB:-postgres}"
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    network_mode: bridge
    depends_on: 
      - postgres
    external_links:
      - postgres-container:postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_EMAIL:-admin@example.com}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_PASSWORD:-admin}"

